baseURL = "https://opensourcestories.org/"
languageCode = "en-us"
title = "Open Source Stories"
theme = "ananke"
copyright = "Open Source Stories,"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 8
enableRobotsTXT = true
googleAnalytics = "G-7TL98FG4D8"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
  [[menu.main]]
    identifier = "storycorp"
    name = "StoryCorps"
    url = "https://archive.storycorps.org/communities/open-source-stories/"

[params]
  favicon = "favicon.ico"
  site_logo = ""
  description = "Narratives of open source"
  twitter = "https://twitter.com/StoriesOfOSS"
  github = "https://github.com/opensourcestories"
  rss = "index.xml"
  featured_image = ""
  recent_posts_number = 4
  background_color_class = "oss-dark-green"
  custom_css = ["opensourcestories.css"]

[author.amanda]
  name = "Amanda Casari"
[author.julia]
  name = "Julia Ferraioli"
