baseURL = "https://www.opensourcestories.org/"
languageCode = "en-us"
title = "Open Source Stories"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
copyright = "The content on Open Source Stories is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true
pagination.pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "contribute"
    name = "Contribute"
    url = "/contribute/"
    weight = 1
  [[menu.main]]
    identifier = "stories"
    name = "Stories"
    url = "/stories/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "News"
    url = "/posts/"
    weight = 8
  [[menu.main]]
    identifier = "storycorp"
    name = "StoryCorps"
    url = "https://archive.storycorps.org/communities/open-source-stories/"
    weight = 10

[params]
  favicon = "favicon.ico"
  site_logo = ""
  description = "The Open Source Stories project celebrates collaboration, communication, community and, more in open source by collecting narratives from creators,  ors, and consumers alike."
  featured_image = ""
  recent_posts_number = 4
  background_color_class = "oss-dark-green"
  custom_css = ["opensourcestories.css"]
  body_classes = "avenir almost-black"

[params.ananke.social.follow]
icons = true
new_window_icon = true
networks = [
  "mastodon",
  "bluesky",
  "linkedin",
  "github",
  "rss"
]

[params.ananke.social.share]
icons = true
networks = [
  "mastodon",
  "bluesky",
  "linkedin",
  "github"
]

[params.ananke.social.mastodon]
  profilelink = "https://fedi.opensourcestories.org/@narrator"

[params.ananke.social.github]
  profilelink = "https://github.com/opensourcestories"

[params.ananke.social.linkedin]
  profilelink = "https://www.linkedin.com/company/open-source-stories"

[params.ananke.social.bluesky]
  profilelink = "https://bsky.app/profile/opensourcestories.org"
  
[params.ananke.social.rss]
  profilelink = "/index.xml"

[params.podcast]
  podcast_author = "Open Source Stories"
  podcast_email = "admin@opensourcestories.org"
  podcast_owner = "julia ferraioli"
  podcast_image = "https://www.opensourcestories.org/images/logos/logo-square-1600x1600.png"
  podcast_category_primary = "Technology"
  podcast_category_secondary = "News"
  podcast_subcategories_secondary = ["Tech News", "News Commentary"]
  podcast_explicit = "no"
  podcast_rss = "/stories/index.xml"

[params.Founder.amanda]
  name = "amanda casari"
[params.Founder.julia]
  name = "julia ferraioli"

[params.storytelling]
  booking_link = "https://cal.com/team/open-source-stories/30-minute-storytelling-session-request"
  booking_copy = "Do you have an Open Source Story that you'd like to tell? Request a storytelling session with one of our facilitators. While we cannot guarantee that we will be able to accommodate every request, we will review each one thoroughly! Please provide as much detail in the scheduling form as possible about the story you'd like to tell."

[permalinks]
  posts = '/posts/:year/:month/:title/'
