baseURL = "https://opensourcestories.org/"
languageCode = "en-us"
title = "Open Source Stories"
theme = "ananke"
copyright = "The content on Open Source Stories is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 8
enableRobotsTXT = true
googleAnalytics = "G-7TL98FG4D8"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
  [[menu.main]]
    identifier = "storycorp"
    name = "StoryCorps"
    url = "https://archive.storycorps.org/communities/open-source-stories/"

[params]
  favicon = "favicon.ico"
  site_logo = ""
  description = "The Open Source Stories project celebrates collaboration, communication, community and, more in open source by collecting narratives from creators, contributors, and consumers alike."
  twitter = "https://twitter.com/StoriesOfOSS"
  github = "https://github.com/opensourcestories"
  rss = "/index.xml"
  featured_image = ""
  recent_posts_number = 4
  background_color_class = "oss-dark-green"
  custom_css = ["opensourcestories.css"]


  [params.podcast]
    podcast_author = "Open Source Stories"
    podcast_email = "admin@opensourcestories.org"
    podcast_owner = "julia ferraioli"
    podcast_image = "images/logos/logo-square.png"
    podcast_category_primary = "Technology"
    podcast_category_secondary = "News"
    podcast_subcategories_secondary = ["Tech News", "News Commentary"]
    podcast_explicit = "no"



[author.amanda]
  name = "Amanda Casari"
[author.julia]
  name = "Julia Ferraioli"
